apiVersion: v1
kind: Service
metadata:
  name: pim-attribute-service
  namespace: microservices
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
    protocol: TCP
  - port: 50051
    name: grpc
    targetPort: 50051
    protocol: TCP
  type: NodePort
  selector:
    app: pim-attribute